admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///flyte.dev.myexample.com:443
  authType: Pkce
  insecure: false
logger:
  show-source: true
  level: 0
